### ISSUE TITLE
[Discussion] Replacing libsolv with pubgrub

### ISSUE THREAD

**Issue by tranzystorek-io** [FyraLabs/anda#2]
I'm not sure what requirements there are for dependency solving in this project, but https://github.com/pubgrub-rs/pubgrub is a pretty mature and pure-rust solver.

**Comment by korewaChino** [comment]
RPM has a custom versioning scheme, NEVRA (name-epoch-version.release.architecture) to be exact.

To use pubgrub this will require it to support such versioning scheme. The solver must prefer packages with the same release as the system's release. Currently libsolv (and in extension, DNF) does this.

**Comment by tranzystorek-io** [comment]
pubgrub operates on dependencies via a Version trait, so most probably the NEVRA scheme could be customly implemented

**Comment by korewaChino** [comment]
Might be viable then. I'll look into it more with @windowsboy111 once we get the time.

**Comment by korewaChino** [comment]
Oh by the way, can pubgrub solve dependencies by file?
