### ISSUE TITLE
feature request: Use rpms in `anda-build` or where ever anda put built rpms

### ISSUE THREAD

**Issue by cat-master21** [FyraLabs/anda#28]
When building a chain/multiple RPMs, it would be useful to install the RPMs anda already built. For example, if there is a mass rebuild (say glibc got update) and libraries depend on each other in Terrapkg, then this would make sure they link to the newer ones that were built.

**Comment by lleyton** [comment]
Anda currently creates an RPM repo in the anda-build directory. Subsequent Anda invocations should include that repo. When building these packages, are you using separate build caches?

**Comment by windowsboy111** [comment]
When I was adding [gendesk](https://github.com/terrapkg/packages/tree/main/anda/go/gendesk) to terra I was able to fully build it locally while it depends on xyproto-env, yhat-scrape, and xyproto-textoutput which depends on xyproto-vt100

It worked fine for me without extra configurations

**Comment by cat-master21** [comment]
Well it would seem I am mistaken as it works now, I just had some other issue(s).

**Comment by lleyton** [comment]
Feel free to open any other issues
