### ISSUE TITLE
Rhai: Runtime error: No version preamble in spec (line 7, position 6)

### ISSUE THREAD

**Issue by getchoo** [FyraLabs/anda#64]
i'm getting this error here (here)[https://github.com/terrapkg/packages/actions/runs/5340646352/jobs/9680694508#step:5:1] when an updated is attempted for prismlauncher-nightly/prismlauncher-qt5-nightly in terrapkg. i'm not really sure what's going on here, and this seems to have only started recently

**Comment by windowsboy111** [comment]
That's partly my issue because I updated the update script to try and use both the version and the commit automatically but I forgot andax doesn't accept macros in version preamble.
